# Generated by Django 5.1.6 on 2025-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('lineOne', models.CharField(max_length=255)),
                ('lineTwo', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'about_me_cards',
            },
        ),
    ]
