# Generated by Django 5.1.6 on 2025-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0002_aboutmecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeinfo',
            name='photo_url',
            field=models.ImageField(upload_to='media/about_me_picture'),
        ),
    ]
