# Generated by Django 5.1.6 on 2025-02-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0003_alter_aboutmeinfo_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmeinfo',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
