# Generated by Django 5.1.6 on 2025-02-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0004_rename_photo_url_aboutmeinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmecard',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
