# Generated by Django 5.1.6 on 2025-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0005_alter_aboutmecard_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeinfo',
            name='photo',
            field=models.ImageField(upload_to='about_me_picture/'),
        ),
    ]
