# Generated by Django 5.1.6 on 2025-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0006_alter_aboutmeinfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmecard',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='about_me_icons/'),
        ),
    ]
