# Generated by Django 5.1.6 on 2025-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0007_aboutmecard_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMeCard',
        ),
        migrations.RemoveField(
            model_name='aboutmeinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutmeinfo',
            name='photo',
        ),
        migrations.AddField(
            model_name='aboutmeinfo',
            name='about_paragraph1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmeinfo',
            name='about_paragraph2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
