# Generated by Django 5.1.6 on 2025-07-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0008_delete_aboutmecard_remove_aboutmeinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeinfo',
            name='about_paragraph1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutmeinfo',
            name='about_paragraph2',
            field=models.TextField(default=''),
        ),
    ]
