# Generated by Django 5.1.6 on 2025-07-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_aboutme', '0009_alter_aboutmeinfo_about_paragraph1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmeinfo',
            name='projects_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutmeinfo',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
