# Generated by Django 5.1.6 on 2025-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0003_remove_profile_resume_url_profile_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_picture'),
        ),
    ]
