# Generated by Django 5.1.6 on 2025-04-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0005_alter_profile_image'),
        ('a_profile', '0005_alter_profile_image_alter_profile_resume'),
    ]

    operations = [
    ]
