# Generated by Django 5.1.6 on 2025-07-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0006_merge_20250413_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_theme',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
