# Generated by Django 5.1.6 on 2025-07-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_profile', '0007_profile_default_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20),
        ),
    ]
