# Generated by Django 5.1.6 on 2025-07-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('current', 'Current'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'careers',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CareerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.TextField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='a_career.career')),
            ],
            options={
                'db_table': 'career_achievements',
            },
        ),
        migrations.CreateModel(
            name='CareerTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technology_name', models.CharField(max_length=255)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='a_career.career')),
            ],
            options={
                'db_table': 'career_technologies',
            },
        ),
        migrations.AddField(
            model_name='career',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='a_career.company'),
        ),
    ]
