# Generated by Django 5.1.6 on 2025-07-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-end_date']},
        ),
    ]
