# Generated by Django 5.1.6 on 2025-07-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_career', '0002_alter_career_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={},
        ),
        migrations.AddField(
            model_name='career',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
