# Generated by Django 5.1.6 on 2025-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('github_link', models.URLField()),
                ('live_link', models.URLField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
