# Generated by Django 5.1.6 on 2025-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_projects', '0005_alter_project_github_link_alter_project_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_pictures/'),
        ),
    ]
