# Generated by Django 5.1.6 on 2025-07-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_projects', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
