# Generated by Django 5.1.6 on 2025-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_projects', '0007_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='show_project',
            field=models.BooleanField(default=True),
        ),
    ]
