# Generated by Django 5.1.6 on 2026-03-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoAppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_name', models.CharField(max_length=50, unique=True)),
                ('apk_file', models.FileField(upload_to='sacco_updates/')),
            ],
            options={
                'verbose_name': 'Sacco App Update',
                'verbose_name_plural': 'Sacco App Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
